/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "signal.h"

reponse *
send_signal_1_svc(data* argp, struct svc_req *rqstp)
{
	static reponse  result;

	printf ("signal process : %d, date : %d, action : %s\n", argp->process, argp->timestamp, argp->action);

	return &result;
}
