/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SIGNAL_H_RPCGEN
#define _SIGNAL_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct data {
	u_int process;
	u_int timestamp;
	char action[99];
};
typedef struct data data;


struct reponse {
	int errno;
};
typedef struct reponse reponse;


#define SIGNAL 0x20000001
#define VERSION_UN 1

#if defined(__STDC__) || defined(__cplusplus)
#define SEND_SIGNAL 0
extern  reponse * send_signal_1(data *, CLIENT *);
extern  reponse * send_signal_1_svc(data *, struct svc_req *);
extern int signal_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SEND_SIGNAL 0
extern  reponse * send_signal_1();
extern  reponse * send_signal_1_svc();
extern int signal_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_data (XDR *, data*);
extern  bool_t xdr_data (XDR *, data*);
extern  bool_t xdr_reponse (XDR *, reponse*);
extern  bool_t xdr_reponse (XDR *, reponse*);

#else /* K&R C */
extern bool_t xdr_data ();
extern bool_t xdr_data ();
extern bool_t xdr_reponse ();
extern bool_t xdr_reponse ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SIGNAL_H_RPCGEN */
