/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "signal.h"

bool_t
xdr_data (XDR *xdrs, data *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_u_int (xdrs, &objp->process))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->timestamp))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->action, 99,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_reponse (XDR *xdrs, reponse *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->errno))
		 return FALSE;
	return TRUE;
}
